//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstWebWithWCF.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tambah", ReplyAction="http://tempuri.org/IService1/TambahResponse")]
        double Tambah(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tambah", ReplyAction="http://tempuri.org/IService1/TambahResponse")]
        System.Threading.Tasks.Task<double> TambahAsync(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Kurang", ReplyAction="http://tempuri.org/IService1/KurangResponse")]
        double Kurang(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Kurang", ReplyAction="http://tempuri.org/IService1/KurangResponse")]
        System.Threading.Tasks.Task<double> KurangAsync(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Kali", ReplyAction="http://tempuri.org/IService1/KaliResponse")]
        double Kali(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Kali", ReplyAction="http://tempuri.org/IService1/KaliResponse")]
        System.Threading.Tasks.Task<double> KaliAsync(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Bagi", ReplyAction="http://tempuri.org/IService1/BagiResponse")]
        double Bagi(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Bagi", ReplyAction="http://tempuri.org/IService1/BagiResponse")]
        System.Threading.Tasks.Task<double> BagiAsync(double num1, double num2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : FirstWebWithWCF.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<FirstWebWithWCF.ServiceReference1.IService1>, FirstWebWithWCF.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Tambah(double num1, double num2) {
            return base.Channel.Tambah(num1, num2);
        }
        
        public System.Threading.Tasks.Task<double> TambahAsync(double num1, double num2) {
            return base.Channel.TambahAsync(num1, num2);
        }
        
        public double Kurang(double num1, double num2) {
            return base.Channel.Kurang(num1, num2);
        }
        
        public System.Threading.Tasks.Task<double> KurangAsync(double num1, double num2) {
            return base.Channel.KurangAsync(num1, num2);
        }
        
        public double Kali(double num1, double num2) {
            return base.Channel.Kali(num1, num2);
        }
        
        public System.Threading.Tasks.Task<double> KaliAsync(double num1, double num2) {
            return base.Channel.KaliAsync(num1, num2);
        }
        
        public double Bagi(double num1, double num2) {
            return base.Channel.Bagi(num1, num2);
        }
        
        public System.Threading.Tasks.Task<double> BagiAsync(double num1, double num2) {
            return base.Channel.BagiAsync(num1, num2);
        }
    }
}
